server:
  port: 8090

spring:
  application:
    name: microservice-vehicle

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://18.116.226.21:3306/especializacion
    username: miguel.especializacion
    password: Miguel123

    hikari:
      maximum-pool-size: 10
      connection-timeout: 3000

  jpa:
    hibernate:
      ddl-auto: none  # No usar 'create' para evitar perder datos
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka